some changes to Dockerfile ...
currently, the issue when running the resulting docker image is
PermissionError: [Errno 13] Permission denied: '/.streamlit'